### ISSUE TITLE
py file opens and closes instantly 

### ISSUE THREAD

**Issue by orytel** [vivinano/MudaeAutoBot#202]
i guess i ve done everything right this is what is shown on idle file its probably a dumb mistake by me but if you can help thx a lot.

[py idle error.txt](https://github.com/vivinano/MudaeAutoBot/files/9446016/py.idle.error.txt)

**Comment by vivinano** [comment]
Post a screenshot I would
Rather avoid downloading things

**Comment by orytel** [comment]
![mudaebot](https://user-images.githubusercontent.com/112413543/187274186-d8bb4673-3527-4b45-adba-6da495e8f2b3.png)

**Comment by vivinano** [comment]
Incorrect json settings

**Comment by orytel** [comment]
uhm how exactly do i fix that ?

**Comment by vivinano** [comment]
That answer is on the readme

**Comment by orytel** [comment]
oh my bad seems to work now but im getting this which says just to type $settings on the server and i did but still not working after restarting 

Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001FBE55B7BA0>>
Traceback (most recent call last):
  File "C:\Users\Orytel\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Orytel\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 686, in on_message
    user = bot.gateway.session.user
  File "C:\Users\Orytel\AppData\Roaming\Python\Python310\site-packages\discum\gateway\session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'
2022-08-29 22:03:46,278:Could not find settings for 992425198789873687, please trigger the '$settings' command in the server and run the bot again.

**Comment by vivinano** [comment]
The channeldata folder is empty obtain the $setting text block from mudae

**Comment by orytel** [comment]
so i use $settings and copy and paste the result on channeldata folder ?

**Comment by vivinano** [comment]
With the bold asterisk and the correct naming scheme

**Comment by orytel** [comment]
i guess the issue is because the $lang aint eng have u tried it on other lenguages ?

**Comment by vivinano** [comment]
No it works in any language there are several mudae players that are playing non English version of mudae

**Comment by orytel** [comment]
does not make any sense then shouldnt this be fine ? 
"Configurações do Server 
 Server Premium I 

 Prefix":$ ("$prefix)
 Lang":"pt-br ($lang)
 Claim reset":"cada 120 min. ($setclaim)
 Minuto exato do reset":"xx":"28 ($setinterval)
 Reset alterada":"por +0 min. ($shifthour)
 Rolls por hora":"15 ($setrolls)
 Tempo antes da reação dos rolls sumir":"45 sec. ($settimer)
 Raridade de spawn para personagens já casados":"6 ($setrare)
 Server game mode":"1 ($gamemode)
 Channel instance":"1 ($channelinstance)
 Slash commands":"ativado ($toggleslash)

 Ranking":"ativado ($toggleclaimrank/$togglelikerank)
 Ranks exibidos durante os rolls":"claims e likes ($togglerolls)
 Séries de Hentai":"desativado ($togglehentai)
 Séries com imagens""Gore":"ativado ($toggledisturbing)
 Rolls sniping":"0 ($togglesnipe)
 Kakera sniping":"0 ($togglekakerasnipe)
 Limite de caracteres por harém":"8100 ($haremlimit)
 Reacts":"apenas para wishes públicas ($togglereact)
 Reações personalizadas":"não ($claimreact)

 Trade de Kakera":"ativado ($togglekakeratrade)
 Cálculo de Kakera":"claim e like rank (e número de personagens casados) ($togglekakeraclaim/$togglekakeralike)
 Valor de kakera exibido durante os rolls":"ativado ($togglekakerarolls)
 $kakeraloot wishprotect":"ativado ($togglewishprotect)"

**Comment by orytel** [comment]
so now this should be a discum issue ? 

Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000018161A87CD0>>
Traceback (most recent call last):
  File "C:\Users\Orytel\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Orytel\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 686, in on_message
    user = bot.gateway.session.user
  File "C:\Users\Orytel\AppData\Roaming\Python\Python310\site-packages\discum\gateway\session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'

**Comment by CriticalMomento** [comment]
> so now this should be a discum issue ?
> 
> Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000018161A87CD0>> Traceback (most recent call last): File "C:\Users\Orytel\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop func(resp) File "C:\Users\Orytel\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 686, in on_message user = bot.gateway.session.user File "C:\Users\Orytel\AppData\Roaming\Python\Python310\site-packages\discum\gateway\session.py", line 42, in user return self.settings_ready['user'] KeyError: 'user'

Go to your discum package folder: /discum/gateway/types.py. Add some type under channelTypes. For instance:
channelTypes = {
0: "guild_text",
1: "dm",
2: "guild_voice",
3: "group_dm",
4: "guild_category",
5: "guild_news",
6: "guild_store",
10: "guild_news_thread",
11: "guild_public_thread",
12: "guild_private_thread",
13: "guild_stage_voice",
14: "type_14",
15: "type_15"
} 
more info in here https://github.com/vivinano/MudaeAutoBot/issues/137
but that should fix it

**Comment by vivinano** [comment]
You need to the the bold asterisk as needed

**Comment by orytel** [comment]
can you show me what a functioning one looks like ?

**Comment by vivinano** [comment]
There is one in the code of a functioning settings I think but if not there several in closed issues

**Comment by orytel** [comment]
still gettings same error for these did i miss something ?




_ __ ** Configurações do Server**_ __
 Server Premium I 

· Prefix: **$** ($prefix)
· Lang: **pt-br** ($lang)
· Claim reset: cada **120** min. ($setclaim)
· Minuto exato do reset: xx:**28** ($setinterval)
· Reset alterada: por +**0** min. ($shifthour)
· Rolls por hora: **15** ($setrolls)
· Tempo antes da reação dos rolls sumir: **45** sec. ($settimer)
· Raridade de spawn para personagens já casados: **6** ($setrare)
· Server game mode: **1** ($gamemode)
· Channel instance: **1** ($channelinstance)
· Slash commands: ativado ($toggleslash)

· Ranking: ativado ($toggleclaimrank/$togglelikerank)
· Ranks exibidos durante os rolls: claims e likes ($togglerolls)
· Séries de Hentai: desativado ($togglehentai)
· Séries com imagens 'Gore': ativado ($toggledisturbing)
· Rolls sniping: **0** ($togglesnipe)
· Kakera sniping: **0** ($togglekakerasnipe)
· Limite de caracteres por harém: **8100** ($haremlimit)
· Reacts: apenas para wishes públicas ($togglereact)
· Reações personalizadas: não ($claimreact)

· Trade de Kakera: **disabled** ($togglekakeratrade)
· Cálculo de Kakera: claim e like rank (e número de personagens casados) ($togglekakeraclaim/$togglekakeralike)
· Valor de kakera exibido durante os rolls: ativado ($togglekakerarolls)
· $kakeraloot wishprotect: ativado ($togglewishprotect)

**Comment by CriticalMomento** [comment]
u added ** for bold in txt file right?

**Comment by orytel** [comment]
yeah the darker ones have the ** it might be something else causing it it's weird

**Comment by vivinano** [comment]
I guess what is the error currently ?

**Comment by vivinano** [comment]
Issues with closing has been fixed now this is a keyword user error so will be closing to keep all user error under 1 issue

**Comment by vivinano** [comment]
If everything else is fixed then it would be a discum issue i haven’t encountered it to fix it
